# Cross-compilation Linux -> Windows x64 avec mingw-w64.
# cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-mingw64.cmake

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(VELYX_MINGW_TRIPLE "x86_64-w64-mingw32" CACHE STRING "mingw-w64 target triple")

find_program(CMAKE_C_COMPILER "${VELYX_MINGW_TRIPLE}-gcc" REQUIRED)
find_program(CMAKE_CXX_COMPILER "${VELYX_MINGW_TRIPLE}-g++" REQUIRED)
find_program(CMAKE_RC_COMPILER "${VELYX_MINGW_TRIPLE}-windres")
find_program(CMAKE_AR "${VELYX_MINGW_TRIPLE}-ar")
find_program(CMAKE_RANLIB "${VELYX_MINGW_TRIPLE}-ranlib")

set(CMAKE_FIND_ROOT_PATH "/usr/${VELYX_MINGW_TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(VELYX_STATIC_RUNTIME_FLAGS "-static-libgcc -static-libstdc++ -static")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${VELYX_STATIC_RUNTIME_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${VELYX_STATIC_RUNTIME_FLAGS}")
